/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package integerSort;

import com.google.common.collect.Lists;

import java.util.ArrayList;
import java.util.List;

public class IntegerSort {
    public List<Integer> sort(List<Integer> numbers) {
        return Lists.newArrayList();
    }
}
