/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package integerSort;

import com.google.common.collect.Lists;

import java.util.ArrayList;
import java.util.List;

public class IntegerSort {
    public List<Integer> sort(List<Integer> numbers) {
        List<Integer> sorted = numbers;

        for(int size = numbers.size();size > 1; size--){
            for (int index = 0;index < size - 1;index++) {
                if (numbers.get(index) > numbers.get(index + 1)) {
                    int temp = numbers.get(index);
                    numbers.set(index, numbers.get(index + 1));
                    numbers.set(index + 1, temp);
                }
            }
        }

        return sorted;
    }
}
