/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package integerSort;

import com.google.common.collect.Lists;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class IntegerSortTests {
    @Test void sortTest() {
        List<Integer> emptyList = Lists.newArrayList();

        assertEquals(Lists.newArrayList(), new IntegerSort().sort(emptyList));
    }
}
