/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package integerSort;

import com.google.common.collect.Lists;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class IntegerSortTests {
    @Test void sortTest() {
        List<Integer> emptyList = Lists.newArrayList();
        List<Integer> singleItemList = Lists.newArrayList(1);
        //  1,2 will already pass...need a failing test
        List<Integer> twoOutOfOrderList = Lists.newArrayList(2, 1);

        assertEquals(Lists.newArrayList(), new IntegerSort().sort(emptyList));
        assertEquals(Lists.newArrayList(1), new IntegerSort().sort(singleItemList));
        assertEquals(Lists.newArrayList(1, 2), new IntegerSort().sort(twoOutOfOrderList));
    }
}
