/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bowling;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class gameTests {
    @Test
    public void someGenericTest() {

    }
}
